In [15]:
import pandas as pd
import numpy as np

In [72]:
df=pd.read_csv("Housing.csv")
df.head()

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,1,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,2,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,3,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,4,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,5,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [74]:
df.tail()

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
541,542,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,543,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,544,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,545,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,546,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  546 non-null    int64
 1   price       546 non-null    float64
 2   lotsize     546 non-null    int64
 3   bedrooms    546 non-null    int64
 4   bathrms     546 non-null    int64
 5   stories     546 non-null    int64
 6   driveway    546 non-null    object
 7   recroom     546 non-null    object
 8   fullbase    546 non-null    object
 9   gashw       546 non-null    object
 10  airco       546 non-null    object
 11  garagepl    546 non-null    int64
 12  prefarea    546 non-null    object
dtypes: float64(1), int64(6), object(6)
memory usage: 55.6+ KB

In [78]:
df.describe()

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,garagepl
count,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000
mean,273.500000,68121.597070,5150.265568,2.965201,1.285714,1.807692,0.692308
std,157.760895,26702.670926,2168.158725,0.737388,0.502158,0.868203,0.861307
min,1.000000,25000.000000,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,137.250000,49125.000000,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,273.500000,62000.000000,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,409.750000,82000.000000,6360.000000,3.000000,2.000000,2.000000,1.000000
max,546.000000,190000.000000,16200.000000,6.000000,4.000000,4.000000,3.000000

In [80]:
df.shape

(546, 13)

In [82]:
df.isna().sum()

Unnamed: 0    0
price         0
lotsize       0
bedrooms      0
bathrms       0
stories       0
driveway      0
recroom       0
fullbase      0
gashw         0
airco         0
garagepl      0
prefarea      0
dtype: int64

In [84]:
from sklearn.preprocessing import LabelEncoder

In [86]:
le=LabelEncoder()
cols={"driveway","recroom","fullbase","gashw","airco","prefarea"}
for f in cols:
    df[f]=le.fit_transform(df[f])
    #null to not-null

In [88]:
df.head()

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,1,42000.0,5850,3,1,2,1,0,1,0,0,1,0
1,2,38500.0,4000,2,1,1,1,0,0,0,0,0,0
2,3,49500.0,3060,3,1,1,1,0,0,0,0,0,0
3,4,60500.0,6650,3,1,2,1,1,0,0,0,0,0
4,5,61000.0,6360,2,1,1,1,0,0,0,0,0,0

In [90]:
#bestfit-corelation(more than 80%)

In [92]:
df.corr()

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
Unnamed: 0,1.000000,0.376007,0.374338,0.114219,0.108395,0.231427,0.314014,0.096721,-0.002034,-0.033494,0.157111,0.125326,0.519994
price,0.376007,1.000000,0.535796,0.366447,0.516719,0.421190,0.297167,0.254960,0.186218,0.092837,0.453347,0.383302,0.329074
lotsize,0.374338,0.535796,1.000000,0.151851,0.193833,0.083675,0.288778,0.140327,0.047487,-0.009201,0.221765,0.352872,0.234782
bedrooms,0.114219,0.366447,0.151851,1.000000,0.373769,0.407974,-0.011996,0.080492,0.097201,0.046028,0.160412,0.139117,0.078953
bathrms,0.108395,0.516719,0.193833,0.373769,1.000000,0.324066,0.041955,0.126892,0.102791,0.067365,0.184955,0.178178,0.064013
stories,0.231427,0.421190,0.083675,0.407974,0.324066,1.000000,0.122499,0.042281,-0.173860,0.018261,0.296216,0.043412,0.042940
driveway,0.314014,0.297167,0.288778,-0.011996,0.041955,0.122499,1.000000,0.091959,0.043428,-0.011942,0.106290,0.203682,0.199378
recroom,0.096721,0.254960,0.140327,0.080492,0.126892,0.042281,0.091959,1.000000,0.372434,-0.010119,0.136626,0.038122,0.161292
fullbase,-0.002034,0.186218,0.047487,0.097201,0.102791,-0.173860,0.043428,0.372434,1.000000,0.004677,0.045248,0.052524,0.228651
gashw,-0.033494,0.092837,-0.009201,0.046028,0.067365,0.018261,-0.011942,-0.010119,0.004677,1.000000,-0.130350,0.068144,-0.059170
airco,0.157111,0.453347,0.221765,0.160412,0.184955,0.296216,0.106290,0.136626,0.045248,-0.130350,1.000000,0.156596,0.115626
garagepl,0.125326,0.383302,0.352872,0.139117,0.178178,0.043412,0.203682,0.038122,0.052524,0.068144,0.156596,1.000000,0.092364
prefarea,0.519994,0.329074,0.234782,0.078953,0.064013,0.042940,0.199378,0.161292,0.228651,-0.059170,0.115626,0.092364,1.000000

In [94]:
x=df[["price"]]
y=df[["lotsize"]]

In [96]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [98]:
from sklearn.linear_model import LinearRegression
slr=LinearRegression()
slr.fit(x_train,y_train)

LinearRegression()

In [100]:
slr.coef_ #slope

array([[0.04518109]])

In [102]:
slr.intercept_ #constant

array([2078.83903784])

In [104]:
ypred=slr.predict(x_test)
ypred

array([[4789.70461112],
       [4586.38969313],
       [4423.73775873],
       [5727.21228855],
       [7952.38111329],
       [4111.9882178 ],
       [3660.17728892],
       [8404.19204218],
       [4315.3031358 ],
       [5331.87772578],
       [5444.830458  ],
       [4699.34242535],
       [5964.41302622],
       [4337.89368224],
       [3208.36636004],
       [3886.08275336],
       [4202.35040358],
       [4428.25586802],
       [6687.31051243],
       [6935.80652331],
       [3795.72056759],
       [6461.40504799],
       [3976.44493914],
       [4789.70461112],
       [5467.42100445],
       [5874.05084044],
       [4428.25586802],
       [5783.68865466],
       [7681.29455596],
       [4789.70461112],
       [5331.87772578],
       [6325.86176932],
       [6009.5941191 ],
       [4834.88570401],
       [5377.05881867],
       [4789.70461112],
       [6145.13739777],
       [5105.97226134],
       [4965.91087339],
       [4812.29515757],
       [7816.83783463],
       [4740.00540895],
       [3547.2245567 ],
       [5015.61007556],
       [6099.95630488],
       [5553.26508093],
       [3614.99619603],
       [8327.38418427],
       [6818.3356818 ],
       [4563.79914668],
       [3818.31111403],
       [5444.830458  ],
       [5196.33444712],
       [6619.53887309],
       [6077.36575844],
       [3750.5394747 ],
       [4111.9882178 ],
       [3208.36636004],
       [5964.41302622],
       [4337.89368224],
       [4563.79914668],
       [4091.88263147],
       [3999.03548558],
       [6371.04286221],
       [4089.39767136],
       [4383.07477513],
       [7161.71198775],
       [4428.25586802],
       [9985.53029326],
       [5919.23193333],
       [5286.69663289],
       [4789.70461112],
       [4947.83843623],
       [4857.47625046],
       [4270.12204291],
       [5399.64936511],
       [4965.91087339],
       [5060.79116845],
       [5196.33444712],
       [6235.49958354],
       [8042.74329907],
       [5444.830458  ],
       [4608.98023957],
       [6642.12941954],
       [5196.33444712],
       [8042.74329907],
       [3976.44493914],
       [5783.68865466],
       [4608.98023957],
       [9081.9084355 ],
       [6280.68067643],
       [4247.53149647],
       [6145.13739777],
       [4066.80712491],
       [5151.15335423],
       [3795.72056759],
       [3298.72854582],
       [7500.57018441],
       [5015.61007556],
       [5869.53273115],
       [4292.71258935],
       [9985.53029326],
       [3547.2245567 ],
       [5467.42100445],
       [4654.16133246],
       [6054.77521199],
       [5241.51554001],
       [4857.47625046],
       [3791.2024583 ],
       [5869.53273115]])

In [106]:
from sklearn.metrics import r2_score

r2_score(y_test,ypred)

0.299353663143043

In [112]:

x_new=np.array([5000]).reshape(1,-1)
slr.predict(x_new)

C:\Users\ghane\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[2304.74450228]])