In [2]:
import pandas as pd
df=pd.read_csv("BMI.csv")
df.head()

   Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [6]:
df.shape

(500, 4)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Gender  500 non-null    object
 1   Height  500 non-null    int64
 2   Weight  500 non-null    int64
 3   Index   500 non-null    int64
dtypes: int64(3), object(1)
memory usage: 15.8+ KB

In [10]:
df.describe()

           Height      Weight       Index
count  500.000000  500.000000  500.000000
mean   169.944000  106.000000    3.748000
std     16.375261   32.382607    1.355053
min    140.000000   50.000000    0.000000
25%    156.000000   80.000000    3.000000
50%    170.500000  106.000000    4.000000
75%    184.000000  136.000000    5.000000
max    199.000000  160.000000    5.000000

In [12]:
df.isna().sum()

Gender    0
Height    0
Weight    0
Index     0
dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Gender"]=le.fit_transform(df["Gender"])
df.head()

   Gender  Height  Weight  Index
0       1     174      96      4
1       1     189      87      2
2       0     185     110      4
3       0     195     104      3
4       1     149      61      3

In [34]:
x=df[["Gender","Height","Weight"]]
y=df.Index

In [36]:
from sklearn.model_selection import train_test_split
train,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)

In [60]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3,metric='euclidean')
knn.fit(xtrain,ytrain)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [64]:
ypred=knn.predict(xtest)
ypred

array([5, 4, 4, 2, 5, 4, 5, 1, 4, 5, 5, 3, 5, 4, 4, 4, 2, 5, 5, 3, 4, 4,
       5, 0, 5, 4, 5, 4, 4, 3, 3, 5, 3, 5, 4, 5, 2, 3, 4, 5, 2, 2, 5, 4,
       5, 3, 5, 5, 2, 5, 4, 0, 3, 2, 5, 0, 2, 5, 5, 3, 2, 0, 5, 5, 1, 5,
       2, 5, 4, 3, 4, 4, 5, 5, 5, 5, 5, 1, 4, 5, 5, 5, 3, 4, 2, 5, 4, 5,
       5, 5, 2, 5, 2, 5, 5, 4, 4, 3, 5, 4], dtype=int64)

In [66]:
from sklearn.metrics import classification_report,accuracy_score
accuracy_score(ytest,ypred)

0.91