In [14]:
import pandas as pd

In [16]:
data=pd.read_csv("apples_and_oranges.csv")

In [18]:
data.head()

   Weight  Size   Class
0      69  4.39  orange
1      69  4.21  orange
2      65  4.09  orange
3      72  5.85   apple
4      67  4.70  orange

In [20]:
data.shape

(40, 3)

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Weight  40 non-null     int64
 1   Size    40 non-null     float64
 2   Class   40 non-null     object
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ KB

In [24]:
data.describe()

          Weight       Size
count  40.000000  40.000000
mean   70.200000   4.922750
std     3.039906   0.590063
min    65.000000   4.010000
25%    68.000000   4.360000
50%    70.000000   4.930000
75%    73.000000   5.472500
max    75.000000   5.850000

In [26]:
data.isna().sum()

Weight    0
Size      0
Class     0
dtype: int64

In [28]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["Class"]=le.fit_transform(data["Class"])

In [30]:
data.head()

   Weight  Size  Class
0      69  4.39      1
1      69  4.21      1
2      65  4.09      1
3      72  5.85      0
4      67  4.70      1

In [67]:
from sklearn.model_selection import train_test_split

x=data[["Weight","Size"]]
y=data.Class
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [71]:
from sklearn.svm import LinearSVC
classifier=LinearSVC()
classifier.fit(xtrain,ytrain)

LinearSVC()

In [75]:
from sklearn.metrics import accuracy_score

In [105]:
ypred=classifier.predict(xtest)
ypred

In [79]:
ypred

array([0, 1, 0, 0, 1, 0, 0, 1])

In [83]:
accuracy_score(ytest,ypred)

1.0

In [97]:
from sklearn.metrics import classification_report,confusion_matrix

In [103]:
confusion_matrix(ytest,ypred)#prediction ratio of correct anf false prediction

array([[5, 0],
       [0, 3]], dtype=int64)