In [100]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,accuracy_score
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix
from sklearn import preprocessing
from sklearn import utils

In [102]:
df=pd.read_csv("synthetic_dataset.csv")

In [104]:
df.head()

   Age  Experience  Education_Level        Salary
0   58          14                1  16921.097283
1   48          22                3  30861.102777
2   34          11                2  14501.793044
3   27          23                3  24461.858981
4   40           1                2   5188.032359

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              1000 non-null   int64
 1   Experience       1000 non-null   int64
 2   Education_Level  1000 non-null   int64
 3   Salary           1000 non-null   float64
dtypes: float64(1), int64(3)
memory usage: 31.4 KB

In [108]:
df.describe()

               Age   Experience  Education_Level        Salary
count  1000.000000  1000.000000      1000.000000   1000.000000
mean     39.991000    20.236000         2.530000  21301.063659
std      11.780055    11.257488         1.136834   7740.643847
min      20.000000     1.000000         1.000000  -3094.085791
25%      30.000000    10.750000         2.000000  16067.850175
50%      41.000000    20.000000         2.000000  21306.864949
75%      50.250000    30.000000         4.000000  26524.981068
max      59.000000    39.000000         4.000000  46249.592780

In [110]:
df.shape

(1000, 4)

In [112]:
df.isna().sum()

Age                0
Experience         0
Education_Level    0
Salary             0
dtype: int64

In [114]:
df.corr()

                      Age  Experience  Education_Level    Salary
Age              1.000000   -0.029045        -0.003306  0.150333
Experience      -0.029045    1.000000         0.001402  0.700488
Education_Level -0.003306    0.001402         1.000000  0.295499
Salary           0.150333    0.700488         0.295499  1.000000

In [116]:
x=df[["Experience"]]
y=df[["Salary"]]

In [118]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [120]:
slr=LinearRegression()
slr.fit(x_train,y_train)

LinearRegression()

In [124]:
ypred=slr.predict(x_test)
ypred

array([[24084.13959833],
       [11882.42474154],
       [21643.79662697],
       [26036.41397542],
       [29452.89413532],
       [21155.7280327 ],
       [15298.90490144],
       [22131.86522125],
       [24572.20819261],
       [19691.52224989],
       [23108.00240979],
       [17739.2478728 ],
       [12858.56193008],
       [11882.42474154],
       [28964.82554105],
       [20179.59084416],
       [18227.31646707],
       [28964.82554105],
       [28964.82554105],
       [30429.03132387],
       [11882.42474154],
       [13346.63052435],
       [20667.65943843],
       [13834.69911863],
       [23108.00240979],
       [14322.7677129 ],
       [17251.17927853],
       [16763.11068426],
       [18227.31646707],
       [18715.38506134],
       [18715.38506134],
       [17251.17927853],
       [19691.52224989],
       [13834.69911863],
       [22131.86522125],
       [15786.97349571],
       [16763.11068426],
       [26524.48256969],
       [19691.52224989],
       [25060.27678688],
       [18227.31646707],
       [16275.04208998],
       [14810.83630717],
       [23108.00240979],
       [17739.2478728 ],
       [25060.27678688],
       [12370.49333581],
       [28964.82554105],
       [24084.13959833],
       [15786.97349571],
       [16275.04208998],
       [30429.03132387],
       [14810.83630717],
       [14322.7677129 ],
       [18715.38506134],
       [12370.49333581],
       [26036.41397542],
       [18715.38506134],
       [27988.68835251],
       [14322.7677129 ],
       [24084.13959833],
       [20667.65943843],
       [19203.45365562],
       [19203.45365562],
       [12370.49333581],
       [11882.42474154],
       [21155.7280327 ],
       [15786.97349571],
       [13346.63052435],
       [18715.38506134],
       [29452.89413532],
       [17739.2478728 ],
       [14810.83630717],
       [17739.2478728 ],
       [22619.93381552],
       [21643.79662697],
       [16275.04208998],
       [23596.07100406],
       [23108.00240979],
       [14322.7677129 ],
       [21155.7280327 ],
       [15298.90490144],
       [23596.07100406],
       [27500.61975824],
       [14322.7677129 ],
       [19691.52224989],
       [14810.83630717],
       [24084.13959833],
       [13834.69911863],
       [26036.41397542],
       [14810.83630717],
       [24084.13959833],
       [20667.65943843],
       [24084.13959833],
       [19691.52224989],
       [16763.11068426],
       [19203.45365562],
       [25548.34538115],
       [18715.38506134],
       [18715.38506134],
       [17251.17927853],
       [18227.31646707],
       [16275.04208998],
       [19691.52224989],
       [19691.52224989],
       [27012.55116396],
       [12370.49333581],
       [12370.49333581],
       [23108.00240979],
       [12858.56193008],
       [29452.89413532],
       [14322.7677129 ],
       [24084.13959833],
       [25060.27678688],
       [25060.27678688],
       [28964.82554105],
       [29940.9627296 ],
       [17739.2478728 ],
       [22619.93381552],
       [15298.90490144],
       [23596.07100406],
       [11882.42474154],
       [27500.61975824],
       [27012.55116396],
       [26036.41397542],
       [19691.52224989],
       [26036.41397542],
       [26524.48256969],
       [28476.75694678],
       [14810.83630717],
       [17739.2478728 ],
       [14322.7677129 ],
       [15298.90490144],
       [28964.82554105],
       [14810.83630717],
       [15298.90490144],
       [22619.93381552],
       [22619.93381552],
       [21155.7280327 ],
       [25060.27678688],
       [27012.55116396],
       [14322.7677129 ],
       [25548.34538115],
       [27988.68835251],
       [11882.42474154],
       [25548.34538115],
       [21155.7280327 ],
       [15786.97349571],
       [18715.38506134],
       [15298.90490144],
       [25060.27678688],
       [30429.03132387],
       [27012.55116396],
       [16275.04208998],
       [29940.9627296 ],
       [23596.07100406],
       [19203.45365562],
       [16275.04208998],
       [19691.52224989],
       [27988.68835251],
       [16763.11068426],
       [15298.90490144],
       [18715.38506134],
       [23596.07100406],
       [13346.63052435],
       [12370.49333581],
       [27012.55116396],
       [19203.45365562],
       [13346.63052435],
       [19691.52224989],
       [27012.55116396],
       [24084.13959833],
       [14810.83630717],
       [21643.79662697],
       [16275.04208998],
       [22131.86522125],
       [21643.79662697],
       [16275.04208998],
       [20179.59084416],
       [13834.69911863],
       [20667.65943843],
       [30429.03132387],
       [29452.89413532],
       [26524.48256969],
       [21643.79662697],
       [21155.7280327 ],
       [15786.97349571],
       [15786.97349571],
       [19691.52224989],
       [17251.17927853],
       [24084.13959833],
       [29452.89413532],
       [18715.38506134],
       [27988.68835251],
       [17251.17927853],
       [28476.75694678],
       [29940.9627296 ],
       [16275.04208998],
       [14810.83630717],
       [13346.63052435]])

In [122]:
slr.coef_

array([[488.06859427]])

In [126]:
r2_score(y_test,ypred)

0.4431461685750935

In [128]:
x_new=np.array([5000]).reshape(1,-1)
slr.predict(x_new)

C:\Users\ghane\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[2451737.32750624]])

In [146]:
x=df[["Experience"]].astype(int)
y=df[["Salary"]].astype(int)

In [148]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [152]:
knn=KNeighborsClassifier(n_neighbors=3,metric='euclidean')
knn.fit(x_train,y_train)

C:\Users\ghane\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [154]:
ypred=knn.predict(x_test)
ypred

array([23507,  8148, 15013, 23913, 28367, 14117, 17447, 20105, 20924,
       15679, 15749, 13379,  7554,  8148, 23784, 18156, 17604, 23784,
       23784, 15998,  8148,    31, 18648, 17585, 15749, 11244, 11286,
       13624, 17604, 16312, 16312, 11286, 15679, 17585, 20105, 11034,
       13624, 26257, 15679, 25085, 17604, 10237, 11560, 15749, 13379,
       25085,  4637, 23784, 23507, 11034, 10237, 15998, 11560, 11244,
       16312,  4637, 23913, 16312, 26502, 11244, 23507, 18648,  9801,
        9801,  4637,  8148, 14117, 11034,    31, 16312, 28367, 13379,
       11560, 13379, 16572, 15013, 10237, 19998, 15749, 11244, 14117,
       17447, 19998, 22357, 11244, 15679, 11560, 23507, 17585, 23913,
       11560, 23507, 18648, 23507, 15679, 13624,  9801, 22590, 16312,
       16312, 11286, 17604, 10237, 15679, 15679, 25530,  4637,  4637,
       15749,  7554, 28367, 11244, 23507, 25085, 25085, 23784, 29662,
       13379, 16572, 17447, 19998,  8148, 22357, 25530, 23913, 15679,
       23913, 26257, 21203, 11560, 13379, 11244, 17447, 23784, 11560,
       17447, 16572, 16572, 14117, 25085, 25530, 11244, 22590, 26502,
        8148, 22590, 14117, 11034, 16312, 17447, 25085, 15998, 25530,
       10237, 29662, 19998,  9801, 10237, 15679, 26502, 13624, 17447,
       16312, 19998,    31,  4637, 25530,  9801,    31, 15679, 25530,
       23507, 11560, 15013, 10237, 20105, 15013, 10237, 18156, 17585,
       18648, 15998, 28367, 26257, 15013, 14117, 11034, 11034, 15679,
       11286, 23507, 28367, 16312, 26502, 11286, 21203, 29662, 10237,
       11560,    31])

In [158]:
accuracy_score(y_test,ypred)

0.0

In [164]:
x_new=np.array([5000]).reshape(-1, 1)
slr.predict(x_new)

C:\Users\ghane\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[2451737.32750624]])

In [172]:
x=df[["Experience"]].astype(int)
y=df[["Salary"]].astype(int)

In [174]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [176]:
classifier=LinearSVC()
classifier.fit(x_train,y_train)

C:\Users\ghane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LinearSVC()

In [178]:
ypred=classifier.predict(x_test)
ypred

array([22357,   436, 22357, 22357, 22357, 13644, 17559, 22357, 22357,
       13644, 22357, 17559, 12703,   436, 22357, 13644, 17559, 22357,
       22357, 22357,   436, 12703, 13644, 12703, 22357, 12703, 17559,
       17559, 17559, 17559, 17559, 17559, 13644, 12703, 22357, 17559,
       17559, 22357, 13644, 22357, 17559, 17559, 12703, 22357, 17559,
       22357,  -409, 22357, 22357, 17559, 17559, 22357, 12703, 12703,
       17559,  -409, 22357, 17559, 22357, 12703, 22357, 13644, 13644,
       13644,  -409,   436, 13644, 17559, 12703, 17559, 22357, 17559,
       12703, 17559, 22357, 22357, 17559, 22357, 22357, 12703, 13644,
       17559, 22357, 22357, 12703, 13644, 12703, 22357, 12703, 22357,
       12703, 22357, 13644, 22357, 13644, 17559, 13644, 22357, 17559,
       17559, 17559, 17559, 17559, 13644, 13644, 22357,  -409,  -409,
       22357, 12703, 22357, 12703, 22357, 22357, 22357, 22357, 22357,
       17559, 22357, 17559, 22357,   436, 22357, 22357, 22357, 13644,
       22357, 22357, 22357, 12703, 17559, 12703, 17559, 22357, 12703,
       17559, 22357, 22357, 13644, 22357, 22357, 12703, 22357, 22357,
         436, 22357, 13644, 17559, 17559, 17559, 22357, 22357, 22357,
       17559, 22357, 22357, 13644, 17559, 13644, 22357, 17559, 17559,
       17559, 22357, 12703,  -409, 22357, 13644, 12703, 13644, 22357,
       22357, 12703, 22357, 17559, 22357, 22357, 17559, 13644, 12703,
       13644, 22357, 22357, 22357, 22357, 13644, 17559, 17559, 13644,
       17559, 22357, 22357, 17559, 22357, 17559, 22357, 22357, 17559,
       12703, 12703])

In [180]:
accuracy_score(y_test,ypred)

0.0

In [186]:
x_new=np.array([5000]).reshape(-1, 1)
classifier.predict(x_new)

C:\Users\ghane\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearSVC was fitted with feature names
  warnings.warn(

array([28314])